version: '3.9'
services:
  backend:
    container_name: shop-server
    build:
      context: ./server
    command: npm run start:prod
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - shop_network

  nginx:
    image: pachalia/nginx1.25.2:latest
    container_name: shop-server
    volumes:
      - ./nginx/certificate:/etc/nginx/certificate
      - ./nginx:/etc/nginx/conf.d
      - ./client:/var/www/andreypachalia.ru
      - ./nginxlogs:/var/log/nginx
    ports:
      - '80:80'
      - '443:443/tcp'
      - '443:443/udp'
    restart: unless-stopped
    networks:
      - shop_network
networks:
  shop_network:
    external: true